FROM ubuntu:latest

COPY . /build

RUN apt-get update -y && \
    apt-get install -y build-essential cmake autoconf libtool libntl-dev libgmp-dev wget sudo pkg-config libfreetype6-dev libfontconfig1-dev lsb-release software-properties-common gnupg curl libmpfr-dev libmpc-dev git libzstd-dev zlib1g-dev
RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    sudo ./llvm.sh 20 && \
    apt-get install -y libmlir-20-dev mlir-20-tools libpolly-20-dev
RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
ENV MLIR_SYS_200_PREFIX=/usr/lib/llvm-20/
ENV TABLEGEN_200_PREFIX=/usr/lib/llvm-20/
ENV PATH="/root/.cargo/bin:${PATH}"
RUN mkdir /server && \
    cd /build && \
    cargo build --release -p analyzer -p analysis-server && \
    cp target/release/analyzer /server && \
    cp target/release/analysis-server /server && \
    cd /server && \
    rm -rf /build && \
    apt clean -y
EXPOSE 8088
ENTRYPOINT ["/server/analysis-server", "--analyzer-path", "/server/analyzer"]

