FROM ubuntu:latest

COPY . /build

RUN apt-get update -y && \
    apt-get install -y build-essential wget curl libfreetype6-dev libfontconfig1-dev git gnupg

RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y

ENV PATH="/root/.cargo/bin:${PATH}"

RUN rustup target add wasm32-unknown-unknown

RUN apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl && \
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg && \
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list && \
    apt-get update -y && \
    apt-get install caddy -y

RUN mkdir /server && \
    cd /build/analysis-webpage && \
    wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.21.14/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf- && \
    ./trunk build --release --cargo-profile=wasm-release && \
    cp -rf dist /dist && \
    cd /dist && \
    rm -rf /build && \
    apt clean -y

ENTRYPOINT ["caddy", "run", "--config", "/dist/Caddyfile"]
