[package]
name = "cachegrind-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
raffine = { path = "../raffine" }
clap.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
melior.workspace = true
tempfile = "3.27.0"
unescaper = "0.2.0"
rusqlite = { version = "0.40.2", features = ["bundled", "fallible_uint"] }
r2d2_sqlite = "0.35.0"
r2d2 = "0.8.10"
indicatif.workspace = true
rayon.workspace = true
sysinfo = { version = "0.39.6", default-features = false, features = ["component"] }
