[package]
name = "analyzer"
version = "0.1.0"
edition = "2024"

[features]
default = []
barvinok = ["dep:barvinok"]
plotters = ["denning/plotters", "dep:plotters"]

[dependencies]
raffine = { path = "../raffine" }
denning = { path = "../denning" }
barvinok = { git = "https://github.com/Roc-Locality/barvinok-rs", rev = "cc72f5071bb7a1a9ec11e228fcb1686c2f8d3f6c", optional = true }
tracing-subscriber.workspace = true
tracing = { workspace = true, features = [
    "max_level_trace",
    "release_max_level_info",
] }
clap.workspace = true
melior.workspace = true
anyhow.workspace = true
symbolica = { version = "1.5.1", default-features = false }
comfy-table = { version = "7.2.2", default-features = false }
ahash = "0.8.12"
serde.workspace = true
serde_json = "1.0.151"
plotters = { version = "0.3.7", default-features = false, features = [
    "svg_backend",
    "line_series",
], optional = true }
