#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import json
import math
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RESULTS_DIR = REPOSITORY_ROOT / "results" / "mlir-contractions"

SERIES = [
    "Simulation Fully (Tiled)",
    "Barvinok (Symbolic)",
    "SALT (Symbolic)",
]

KERNEL_ORDER = [
    "3D Tensor Vector",
    "4D Tensor",
    "Attention Score",
    "Batched GEMM",
    "Context Lookup",
    "Matrix Matrix",
    "Matrix Vector",
    "Rowwise SoftMax",
]


def format_seconds_plain(seconds: float, max_digits: int = 6) -> str:
    """Format seconds without scientific notation."""
    text = f"{seconds:.{max_digits}f}".rstrip("0").rstrip(".")
    return f"{text}s"


def format_bar_label(label: str, seconds: float) -> str:
    if label == "SALT (Symbolic)":
        return f"{seconds:.4f}s"
    return format_seconds_plain(seconds, max_digits=2)


def geomean(seconds):
    """Geometric mean is a better summary for benchmark-style timing ratios."""
    return math.exp(sum(math.log(value) for value in seconds) / len(seconds))


def load_selected_seconds(data_path: Path):
    """Load measured seconds aligned to KERNEL_ORDER, with a geomean row first."""
    with data_path.open() as stream:
        document = json.load(stream)
    measurements = document["measurements"]
    values = {}
    for label in SERIES:
        if label not in measurements:
            raise ValueError(f"missing timing series: {label}")
        kernel_seconds = [float(measurements[label][kernel]) for kernel in KERNEL_ORDER]
        if any(value <= 0 for value in kernel_seconds):
            raise ValueError(f"all timings must be positive in series: {label}")
        values[label] = [geomean(kernel_seconds), *kernel_seconds]
    return values


def plot_selected(data_path: Path, out_path: str, dpi=600):
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    values = load_selected_seconds(data_path)
    all_seconds = [seconds for series in values.values() for seconds in series]
    min_sec = min(seconds for seconds in all_seconds if seconds > 0)
    max_sec = max(all_seconds)
    plot_order = ["Geomean", *KERNEL_ORDER]

    fig = plt.figure(figsize=(10, 5))
    ax = plt.gca()

    base_y = list(range(len(plot_order)))
    n_series = len(SERIES)
    offset = 0.20
    height = 0.14

    y_per_series = []
    x_per_series = []
    for i, label in enumerate(SERIES):
        y = [y0 + offset * (n_series - 1) / 2.0 - i * offset for y0 in base_y]
        x = values[label]
        ax.barh(y, x, height=height, label=label)
        y_per_series.append(y)
        x_per_series.append(x)

    for kernel_idx in range(len(plot_order)):
        for series_idx in range(n_series):
            label = SERIES[series_idx]
            seconds = x_per_series[series_idx][kernel_idx]
            y = y_per_series[series_idx][kernel_idx]
            ax.annotate(
                format_bar_label(label, seconds),
                xy=(seconds, y),
                xytext=(1, -4),
                textcoords="offset points",
                va="center",
                ha="left",
                fontsize=11.0,
                color="black",
                clip_on=False,
            )

    ax.set_yticks(base_y)
    ax.set_yticklabels(plot_order, fontweight="bold", fontsize=14)
    # ax.set_title("Selected Timing Comparison", fontweight="bold", fontsize=13)
    ax.set_xlabel("Time (seconds, log scale)", fontweight="bold", fontsize=14)
    ax.set_xscale("log")
    left_lim = max(min_sec / 1.8, 1e-6)
    right_lim = max_sec * 4.0
    ax.set_xlim(left_lim, right_lim)
    ticks = [
        10 ** exponent
        for exponent in range(math.floor(math.log10(left_lim)), math.ceil(math.log10(right_lim)) + 1)
        if left_lim <= 10 ** exponent <= right_lim
    ]
    ax.set_xticks(ticks)
    ax.set_xticklabels([format_seconds_plain(tick) for tick in ticks])
    ax.xaxis.set_minor_formatter(NullFormatter())
    ax.grid(True, axis="x", linestyle=":", alpha=0.6)

    legend = fig.legend(
        frameon=False,
        ncols=len(SERIES),
        loc="upper right",
        bbox_to_anchor=(0.90, 0.90),
    )
    if legend is not None:
        for text in legend.get_texts():
            text.set_fontweight("bold")
            text.set_fontsize(14)

    for tick in ax.get_xticklabels():
        tick.set_fontweight("bold")
        tick.set_fontsize(10)

    fig.subplots_adjust(top=0.82)
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    print(f"Saved plot to: {out_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Plot selected timing series in one panel."
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=DEFAULT_RESULTS_DIR / "timing-selected.json",
        help="JSON timing manifest generated by measure_timing_selected.py",
    )
    parser.add_argument(
        "--out",
        default=DEFAULT_RESULTS_DIR / "timing-selected.svg",
        help="Output path for the selected timing plot.",
    )
    parser.add_argument("--dpi", type=int, default=600)
    args = parser.parse_args()

    plot_selected(args.data, args.out, args.dpi)


if __name__ == "__main__":
    main()
